name: build
on:
  push:
  pull_request:
  schedule:
    # weekly builds to make sure it works with the latest version of Guix
    - cron: '39 3 * * 0'
jobs:
  build-with-guix:
    name: make distcheck - guix
    runs-on: ubuntu-latest
    steps:
      - name: Install GNU Guix
        uses: PromyLOPh/guix-install-action@v1
        with:
          pullAfterInstall: false
          channels: |-
            (list
              (channel
                (name 'guix)
                (url "https://git.guix.gnu.org/guix.git")
                (branch "master")
                (commit "8ce414a206206c6f9aa4297143a916ff26ba497d")
                (introduction
                 (make-channel-introduction
                  "9edb3f66fd807b096b48283debdcddccfea34bad"
                  (openpgp-fingerprint
                   "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA")))))
      - name: Describe Guix
        run: |
          /var/guix/profiles/per-user/root/current-guix/bin/guix describe -f channels
          echo "guix-commit=$(/var/guix/profiles/per-user/root/current-guix/bin/guix describe | grep commit | join -a1 -o1.2 - /dev/null)" >> $GITHUB_OUTPUT
        id: guix-commit
      - name: Guix cache
        id: guix-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/guix
          key: guix-cache-${{ steps.guix-commit.outputs.guix-commit }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Guix environment
        if: steps.guix-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/guix
          /var/guix/profiles/per-user/root/current-guix/bin/guix shell --root=env -D -f guix.scm -- echo done
          /var/guix/profiles/per-user/root/current-guix/bin/guix archive --export --recursive $(readlink -f env) > ~/.cache/guix/env
          cp /etc/guix/signing-key.pub ~/.cache/guix/
      - name: Authorize cached signing key
        if: steps.guix-cache.outputs.cache-hit == 'true'
        run: |
          cat ~/.cache/guix/signing-key.pub | sudo /var/guix/profiles/per-user/root/current-guix/bin/guix archive --authorize
      - name: Import Guix environment
        if: steps.guix-cache.outputs.cache-hit == 'true'
        run: |
          du -sh ~/.cache/guix/env
          file ~/.cache/guix/env
          ls -la ~/.cache/guix/env
          cat ~/.cache/guix/env | sudo /var/guix/profiles/per-user/root/current-guix/bin/guix archive --import
          echo imported
      - name: Bootstrap
        run: /var/guix/profiles/per-user/root/current-guix/bin/guix shell -D -f guix.scm -- ./bootstrap.sh
      - name: Configure
        run: /var/guix/profiles/per-user/root/current-guix/bin/guix shell -D -f guix.scm -- ./configure
      - name: Build
        run: /var/guix/profiles/per-user/root/current-guix/bin/guix shell -D -f guix.scm -- make -j
      - name: Distcheck
        env:
          VERBOSE: "true"
        run: /var/guix/profiles/per-user/root/current-guix/bin/guix shell -D -f guix.scm -- make distcheck
  build-with-micromamba:
    name: make distcheck - micromamba
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: requirements.yaml
          cache-environment: true
          post-cleanup: 'all'
          generate-run-shell: true
      - name: Bootstrap
        run: ./bootstrap.sh
        shell: micromamba-shell {0}
      - name: Configure
        run: ./configure
        shell: micromamba-shell {0}
      - name: Build
        run: make -j
        shell: micromamba-shell {0}
      - name: Distcheck
        env:
          VERBOSE: "true"
        run: make distcheck
        shell: micromamba-shell {0}
        
