name: build
on:
  push:
  pull_request:
  schedule:
    # weekly builds to make sure it works with the latest version of Guix
    - cron: '39 3 * * 0'
jobs:
  build:
    name: make distcheck
    runs-on: ubuntu-latest
    steps:
      - name: Install GNU Guix
        uses: PromyLOPh/guix-install-action@v1.3
        with:
          pullAfterInstall: false
      - name: Describe Guix
        run: echo "::set-output name=guix-commit::$(guix describe | grep commit | join -a1 -o1.2 - /dev/null)"
        id: guix-commit
      - name: Guix cache
        id: guix-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/guix
          key: guix-cache-${{ steps.guix-commit.outputs.guix-commit }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Capture Version
        run: |
          cat VERSION
          echo "version=$(cat VERSION)" >> $GITHUB_ENV
      - name: Build Guix environment
        if: steps.guix-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/guix
          guix environment -l guix.scm --root=env -- echo done
          guix archive --export --recursive $(readlink -f env) > ~/.cache/guix/env
          cp /etc/guix/signing-key.pub ~/.cache/guix/
      - name: Authorize cached signing key
        if: steps.guix-cache.outputs.cache-hit == 'true'
        run: |
          cat ~/.cache/guix/signing-key.pub | sudo guix archive --authorize
      - name: Import Guix environment
        if: steps.guix-cache.outputs.cache-hit == 'true'
        run: |
          du -sh ~/.cache/guix/env
          cat ~/.cache/guix/env | sudo guix archive --import
      - name: Bootstrap
        run: guix shell -D -f guix.scm -- ./bootstrap.sh
      - name: Set PICARDJAR
        id: set_picardjar
        run: |
          eval "$(guix shell -D -f guix.scm --search-paths)"
          export PICARDJAR="$GUIX_ENVIRONMENT/share/java/picard.jar"
          echo $PICARDJAR
          echo "PICARDJAR=$PICARDJAR" >> $GITHUB_ENV
      - name: Configure
        run: | 
          guix shell -D -f guix.scm -- ./configure
      - name: Build
        run: guix shell -D -f guix.scm -- make -j
      - name: Distcheck
        id: distcheck
        run: guix shell -D -f guix.scm -- make distcheck
      - name: Print Test Suite Log
        if: steps.distcheck.outcome == 'failure'
        run: cat ${{ github.workspace }}/pigx_bsseq-${{ env.version }}/_build/sub/test-suite.log 
      - name: Upload Test Suite Log
        if: steps.distcheck.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          # https://github.com/actions/upload-artifact#environment-variables-and-tilde-expansion
          name: test-suite.log
          path: ${{ github.workspace }}/pigx_bsseq-${{ env.version }}/_build/sub/test-suite.log
